version: '2'

# See https://github.com/google/cadvisor
services:
  cadvisor:
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8088:8080'
    container_name: cadvisor
    image: 'google/cadvisor:latest'
    restart: unless-stopped