version: "2"
services:
  grafana:
    image: "grafana/grafana:latest"
    container_name: "grafana_grafana"
    ports:
      - "3300:3000"
    volumes:
      - "grafana_storage:/var/lib/grafana"
    environment:
      - "GF_SERVER_ROOT_URL=http://shuttlenas:3300"
    restart: unless-stopped
    networks:
      - grafana_net
  
  influxdb:
    image: "influxdb:latest"
    container_name: "grafana_influx"
    ports:
      - "8086:8086"
    volumes:
      - "grafana_influxdb:/var/lib/influxdb"
    environment:
      - "INFLUXDB_GRAPHITE_ENABLED=true"
      #- "INFLUXDB_ADMIN_USER=detlefs"
      #- "INFLUXDB_ADMIN_PASSWORD=K1ngk0ng"
    restart: unless-stopped
    networks:
      - grafana_net
  
  chronograf:
    image: "chronograf:latest"
    container_name: "grafana_chronograf"
    ports:
      - "8888:8888"
    volumes:
      - "grafana_chronograf:/var/lib/chronograf"
    restart: unless-stopped
    networks:
      - grafana_net
  
  kapatitor:
    image: "kapacitor:latest"
    container_name: "grafana_kapacitor"
    ports:
      - "9092:9092"
    volumes:
      - "grafana_kapacitor:/var/lib/kapacitor"
    environment:
      - "KAPACITOR_HOSTNAME=shuttlenas"
      - "KAPACITOR_INFLUXDB_0_URLS_0=http://192.168.178.64:8086"
    networks:
      - grafana_net
    restart: unless-stopped

networks:
  grafana_net: