version: '2'
services:
    mitmproxy:
        container_name: mitmproxy
        ports:
            - '8080:8080'
            - '8081:8081'
        image: mitmproxy/mitmproxy:latest
        command: mitmweb --web-iface 0.0.0.0
        restart: unless-stopped