version: "2"
services:
  openhab:
    image: "openhab/openhab:latest"
    container_name: openhab
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "openhab_conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
      - "openhab_addons:/openhab/addons"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - OPENHAB_HTTP_PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped
