version: '2'

# Inspired by https://creekorful.me/how-to-install-traefik-2-docker-swarm/
services:
  reverseproxy:
    image: traefik:latest
    container_name: reverse-proxy_traefik
    command:
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      #- "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public

networks:
  traefik-public:
    external:
      name: traefik-public